"""DeepAgents-based LLM executor for the Atelier brick.

Replaces SDKExecutor with a LangChain/DeepAgents agent that supports
native streaming (token-by-token) and multi-provider models.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
from dataclasses import dataclass
from typing import Any, Callable, Awaitable, cast

from deepagents.backends import BackendProtocol, CompositeBackend, LocalShellBackend
from deepagents import SubAgent
from langchain_core.tools import BaseTool
from langchain_core.runnables import RunnableConfig
from langchain.chat_models import BaseChatModel, init_chat_model
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.checkpoint.memory import MemorySaver

from deepagents import create_deep_agent
from common.config_loader import get_relais_home
from common.profile_loader import ProfileConfig
from atelier.display_config import DisplayConfig
from atelier.message_serializer import serialize_messages
from atelier.errors import AgentExecutionError, ExhaustedRetriesError, ToolErrorGuard
from atelier.streaming import STREAM_BUFFER_CHARS, StreamBuffer, _extract_thinking, _has_tool_use_block

# Re-export for backward compatibility — callers do
# ``from atelier.agent_executor import AgentExecutionError`` etc.
__all__ = [
    "AgentExecutionError",
    "ExhaustedRetriesError",
    "ToolErrorGuard",
]
from common.contexts import CTX_AIGUILLEUR, CTX_PORTAIL, AiguilleurCtx, PortailCtx
from common.envelope import Envelope

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class AgentResult:
    """Immutable result of a single agentic turn.

    Attributes:
        reply_text: The final text reply produced by the agent (may be an
            empty string when only tool calls were made).
        messages_raw: Serialized flat list of all LangChain messages captured
            from the agent graph state after the turn completes.  Each element
            is a JSON-serializable dict as produced by ``serialize_messages()``.
        tool_call_count: Total number of tool invocations during the turn.
        tool_error_count: Number of tool invocations that returned
            ``status="error"`` during the turn.
    """

    reply_text: str
    messages_raw: list[dict]
    tool_call_count: int = 0
    tool_error_count: int = 0


REPLY_PLACEHOLDER = "[No response generated by the model.]"
# Marker injected by DeepAgents FilesystemMiddleware into the execute tool's text output
# when the shell command exits with a non-zero code. Used to detect logical failures
# on ToolMessages that carry status="success" at the LangChain level.
_EXECUTE_FAILURE_MARKER = "[Command failed with exit code"
LONG_TERM_MEMORY_PROMPT = """
Long-term memory:
- Any information about the user must be stored in the `memories` directory.
- This includes the user's preferences, needs, goals, projects, and any other user-related details.
- If the user asks you to remember anything, save it in `memories`.
- Always use paths like `/memories/...` to create, read, update, or organize persistent memories.
- Do not write long-term information outside `/memories/`.
- Before answering any question about the user or long-term memory, first check `/memories/` for relevant user and long-term information.
""".strip()

SELF_DIAGNOSIS_PROMPT = """
Self-diagnosis on tool errors (IMPORTANT):
If you encounter repeated tool errors (3+ in a row for the same tool, or 5+ total):
1. STOP retrying the same approach immediately.
2. Re-read the relevant SKILL.md troubleshooting section for the skill you are using.
3. Analyze ALL error messages you have received to identify the root cause.
4. Form a hypothesis about what is wrong (wrong syntax, wrong config key, wrong flag position, etc.).
5. Try ONE corrected approach based on your diagnosis.
Never blindly retry a failing command with minor variations — diagnose first.
""".strip()


# Error class names raised by LLM providers (anthropic, openai, google, …) that
# indicate a transient condition — caller must NOT ACK the message so it stays in
# the PEL for automatic re-delivery.  We detect by name to stay provider-agnostic
# and avoid importing provider SDKs directly.
_TRANSIENT_ERROR_NAMES: frozenset[str] = frozenset(
    {
        "RateLimitError",
        "InternalServerError",
        "APIConnectionError",
        "APITimeoutError",
        "ServiceUnavailableError",
    }
)

# Substrings matched (case-insensitive) inside a ValueError message to detect
# upstream rate-limit or throttle errors forwarded as plain ValueError by
# proxy layers (e.g. OpenRouter wrapping Alibaba / other upstream providers).
_TRANSIENT_VALUE_ERROR_PATTERNS: tuple[str, ...] = (
    "rate limit",
    "rate increased too quickly",
    "too many requests",
    "upstream error",
    "code: 502",
    "code: 503",
    "overloaded",
)


def _resolve_profile_model(
    profile: ProfileConfig,
) -> BaseChatModel | str:
    """Build the model argument for create_deep_agent from a ProfileConfig.

    When both base_url and api_key_env are None, returns the model string
    directly so create_deep_agent can resolve the provider internally.
    When either is set, constructs a BaseChatModel via init_chat_model(),
    passing only the kwargs that are present.

    Args:
        profile: The resolved ProfileConfig for the current envelope.

    Returns:
        Either the model identifier string, or a pre-built BaseChatModel
        instance with the configured endpoint and credentials.

    Raises:
        KeyError: api_key_env is set but the environment variable is absent.
    """
    needs_init = (
        profile.base_url is not None
        or profile.api_key_env is not None
        or profile.parallel_tool_calls is not None
    )
    if not needs_init:
        return profile.model
    kwargs: dict[str, Any] = {}
    if profile.base_url is not None:
        kwargs["base_url"] = profile.base_url
    if profile.api_key_env is not None:
        api_key = os.environ.get(profile.api_key_env)
        if api_key is None:
            raise KeyError(
                f"Environment variable '{profile.api_key_env}' (required by profile "
                f"'{profile.model}') is not set."
            )
        kwargs["api_key"] = api_key
    if profile.parallel_tool_calls is not None:
        kwargs.setdefault("model_kwargs", {})["parallel_tool_calls"] = profile.parallel_tool_calls
    return init_chat_model(profile.model, **kwargs)


def _is_transient_provider_error(exc: BaseException) -> bool:
    """Return True if *exc* is a known transient provider error.

    Two detection strategies:
    - Class name match against ``_TRANSIENT_ERROR_NAMES`` (provider SDK errors).
    - Substring match on ``ValueError`` messages for proxy layers (e.g.
      OpenRouter forwarding upstream rate-limit / 502 errors as plain
      ``ValueError`` rather than a typed SDK exception).

    Args:
        exc: The exception to classify.

    Returns:
        True if the error is transient and the caller should not ACK the message.
    """
    if type(exc).__name__ in _TRANSIENT_ERROR_NAMES:
        return True
    if isinstance(exc, ValueError):
        msg = str(exc).lower()
        return any(pattern in msg for pattern in _TRANSIENT_VALUE_ERROR_PATTERNS)
    return False


def _normalise_content(raw: object) -> str:
    """Normalise a message content field to a plain string.

    Handles the three shapes LangChain message content can take:
    - ``str`` — returned as-is.
    - ``list`` — elements may be ``str`` (joined directly) or ``dict`` blocks
      (only ``{"type": "text", "text": "..."}`` blocks are extracted; other
      block types such as ``image_url``, ``thinking``, ``tool_use`` are
      silently skipped).
    - anything else — converted via ``str()``.

    Args:
        raw: The raw ``.content`` value from a LangChain message.

    Returns:
        A plain string representation of the content.
    """
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        parts: list[str] = []
        for item in raw:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                parts.append(item["text"])
        return "".join(parts)
    return str(raw)


class AgentExecutor:
    """Execute LLM requests via a DeepAgents compiled state graph.

    Wraps `create_deep_agent` and exposes a single `execute()` coroutine
    that streams tokens and progress events via the v2 astream protocol.

    Args:
        profile: Profile config with at least a `.model` attribute
                 (format: ``provider:model-id``).
        soul_prompt: System prompt assembled by SoulAssembler.
        tools: List of LangChain tools (StructuredTool / BaseTool) to
               expose to the agent.
        skills: List of absolute directory paths to skill directories,
                passed directly to ``create_deep_agent(skills=...)``.
                Defaults to an empty list (no skills injected).
        backend: Optional backend instance used for ``/memories/`` paths
                 inside the ``CompositeBackend``.  When ``None`` (default),
                 a ``LocalShellBackend`` rooted at ``RELAIS_HOME`` is used
                 for both the default route and the ``/memories/`` route.
        checkpointer: LangGraph checkpoint saver for persistent conversation
                      history across turns.  When ``None`` (default), falls
                      back to a per-instance ``MemorySaver`` (volatile —
                      history lost on restart).  Pass an ``AsyncSqliteSaver``
                      owned by the Atelier singleton for cross-restart
                      persistence.
        subagents: List of SubAgent specs (dicts with ``name``,
                   ``description``, ``system_prompt``, and optionally
                   ``model``, ``tools``, ``skills``).  Each spec is
                   registered as a child agent invocable via the ``task``
                   tool.  Defaults to an empty list (no subagents).
        delegation_prompt: Pre-assembled delegation prompt from the
                   subagent registry.  Appended to the system prompt so
                   the main agent knows when to delegate via ``task()``.
                   Empty string means no delegation instructions.
        display_config: Display configuration controlling which events and
                   tokens are published to the channel. When None (default),
                   a default DisplayConfig is used (all events enabled,
                   final_only=True).
    """

    def __init__(
        self,
        profile: ProfileConfig,
        soul_prompt: str,
        tools: list[BaseTool],
        skills: list[str] | None = None,
        backend: BackendProtocol | None = None,
        checkpointer: BaseCheckpointSaver | None = None,
        subagents: list[dict[str, Any]] | None = None,
        delegation_prompt: str = "",
        display_config: DisplayConfig | None = None,
    ) -> None:
        self._profile = profile
        self._display = display_config or DisplayConfig()
        memories_backend: BackendProtocol = backend or LocalShellBackend(
            root_dir=str(get_relais_home()), virtual_mode=False, inherit_env=True
        )
        composite_backend = CompositeBackend(
            default=LocalShellBackend(root_dir=str(get_relais_home()), virtual_mode=False, inherit_env=True),
            routes={
                "/memories/": memories_backend,
            },
        )
        # Convert dict subagent specs to SubAgent objects
        compiled_subagents: list[SubAgent] = [
            SubAgent(**spec) for spec in (subagents or [])
        ]
        resolved_skills = skills or []
        self._agent = create_deep_agent(
            model=_resolve_profile_model(profile),
            tools=tools,
            system_prompt=_enrich_system_prompt(
                soul_prompt, delegation_prompt=delegation_prompt,
            ),
            skills=resolved_skills,
            backend=composite_backend,
            checkpointer=checkpointer or MemorySaver(),
            subagents=cast(list[SubAgent | Any], compiled_subagents),
        )
        logger.info(
            "agent.init — model=%s skills=%d %s tools=%d",
            profile.model,
            len(resolved_skills),
            [os.path.basename(s) for s in resolved_skills],
            len(tools),
        )
        if tools:
            tool_names = [t.name for t in tools]
            logger.info(
                "agent.init — mcp_tools=%d names=%s%s",
                len(tool_names),
                tool_names[:10],
                " (truncated)" if len(tool_names) > 10 else "",
            )

    async def execute(
        self,
        envelope: Envelope,
        stream_callback: Callable[[str], Awaitable[None]] | None = None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
    ) -> AgentResult:
        """Run the agent on *envelope* with retry-on-transient-error logic.

        Wraps ``_run_once()`` in a retry loop driven by the profile's
        ``resilience`` configuration.  On each transient error the coroutine
        sleeps for the configured backoff delay before retrying.  When all
        attempts are exhausted, raises ``ExhaustedRetriesError`` (a subclass
        of ``AgentExecutionError``) so the caller routes the message to the DLQ
        and ACKs it — preventing the PEL from being poisoned indefinitely.

        Non-transient errors are wrapped in ``AgentExecutionError`` immediately
        on the first attempt.

        Args:
            envelope: Incoming message envelope; `.content` is the user turn.
            stream_callback: Async callable receiving buffered text chunks.
                If ``None``, no token-by-token streaming is performed.
            progress_callback: Async callable receiving ``(event, detail)`` pairs
                that describe pipeline progress (tool calls, tool results, subagent
                starts).  If ``None``, progress events are only logged locally.

        Returns:
            An ``AgentResult`` containing the full reply text and the serialized
            message list for the completed turn.

        Raises:
            AgentExecutionError: Non-transient failure on the first attempt.
            ExhaustedRetriesError: All retry attempts exhausted on a transient error.
        """
        resilience = self._profile.resilience
        last_exc: BaseException | None = None

        for attempt in range(resilience.retry_attempts + 1):
            try:
                return await self._run_once(envelope, stream_callback, progress_callback)
            except AgentExecutionError:
                raise
            except Exception as exc:
                if not _is_transient_provider_error(exc):
                    raise AgentExecutionError(f"Agent execution failed: {exc}") from exc
                last_exc = exc
                if attempt < resilience.retry_attempts:
                    delay = (
                        resilience.retry_delays[
                            min(attempt, len(resilience.retry_delays) - 1)
                        ]
                        if resilience.retry_delays
                        else 0
                    )
                    logger.warning(
                        "[%s] Transient error (attempt %d/%d), retrying in %ds: %s",
                        envelope.correlation_id,
                        attempt + 1,
                        resilience.retry_attempts,
                        delay,
                        exc,
                    )
                    await asyncio.sleep(delay)

        raise ExhaustedRetriesError(
            f"All {resilience.retry_attempts} retries exhausted: {last_exc}"
        ) from last_exc

    async def _run_once(
        self,
        envelope: Envelope,
        stream_callback: Callable[[str], Awaitable[None]] | None = None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
    ) -> AgentResult:
        """Execute a single agent turn without retry logic.

        Builds the RunnableConfig, runs the astream loop, captures the final
        graph state, and returns the serialized result.  All exceptions
        propagate to the caller (``execute()``).

        Args:
            envelope: Incoming message envelope; `.content` is the user turn.
            stream_callback: Forwarded to ``_stream()``.
            progress_callback: Forwarded to ``_stream()``.

        Returns:
            An ``AgentResult`` for this single attempt.
        """
        exec_context = _build_execution_context(envelope)
        user_content = f"{exec_context}\n\n{envelope.content}" if exec_context else envelope.content
        messages = [{"role": "user", "content": user_content}]
        logger.info(
            "agent.execute start — correlation_id=%s sender=%s",
            envelope.correlation_id,
            envelope.sender_id,
        )
        portail_ctx: PortailCtx = envelope.context.get(CTX_PORTAIL, {})  # type: ignore
        user_id = portail_ctx.get("user_id", envelope.sender_id)
        config = RunnableConfig(configurable={"thread_id": f"{user_id}:{envelope.session_id}"})
        try:
            reply, tool_call_count, tool_error_count = await self._stream(
                {"messages": messages}, stream_callback, progress_callback, config=config
            )
        except AgentExecutionError as exc:
            # Attempt to capture the partial conversation state so that an
            # error-synthesis LLM call can produce a user-visible explanation.
            try:
                state = await self._agent.aget_state(config)
                partial_messages = serialize_messages(state.values.get("messages", []))
                exc.messages_raw = partial_messages
            except Exception:
                pass  # best-effort; messages_raw stays []
            raise
        # Capture full message list from the agent graph state.
        # aget_state() must not fail — if it does, it means the agent is
        # misconfigured (e.g. no checkpointer).  Propagate the exception
        # to execute(): transient errors are retried, others go to DLQ.
        state = await self._agent.aget_state(config)
        state_messages = state.values.get("messages", [])
        messages_raw = serialize_messages(state_messages)
        logger.info(
            "agent.execute done — correlation_id=%s reply_len=%d messages=%d "
            "tool_calls=%d tool_errors=%d",
            envelope.correlation_id,
            len(reply),
            len(messages_raw),
            tool_call_count,
            tool_error_count,
        )
        return AgentResult(
            reply_text=reply,
            messages_raw=messages_raw,
            tool_call_count=tool_call_count,
            tool_error_count=tool_error_count,
        )

    async def _stream(
        self,
        input_data: dict[str, list[dict[str, str]]],
        stream_callback: Callable[[str], Awaitable[None]] | None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
        config: RunnableConfig | None = None,
    ) -> tuple[str, int, int]:
        """Stream tokens and events from the agent, logging all operations.

        Uses the v2 streaming format with ``stream_mode=["updates", "messages"]``
        and ``subgraphs=True`` to capture step transitions, tool calls, tool
        results, and text tokens from both the main agent and any subagents.

        When *stream_callback* is not None, text tokens are forwarded via
        ``StreamBuffer`` (STREAM_BUFFER_CHARS threshold).  Tool error limits are
        enforced by ``ToolErrorGuard``.

        When *progress_callback* is not None, it is called with ``(event, detail)``
        pairs for:
        - ``('tool_call', tool_name)`` — when a tool call is initiated.
        - ``('tool_result', 'name: preview')`` — when a tool result arrives
          (preview capped at 100 characters).
        - ``('subagent_start', source)`` — when a subagent starts an LLM call
          (only emitted for non-root namespaces).

        Falls back to the last ToolMessage content when the model emits no AI
        text tokens (nemotron-mini pattern).  Returns a placeholder constant
        when neither AI text nor tool results are available.

        Args:
            input_data: Input dict passed to ``agent.astream``.
            stream_callback: Async callable receiving flushed text chunks,
                or ``None`` for logging-only mode.
            progress_callback: Async callable receiving ``(event, detail)``
                pipeline progress pairs, or ``None`` to skip progress events.

        Returns:
            A 3-tuple of ``(reply, tool_call_count, tool_error_count)`` where
            *reply* is the complete text assembled from all streamed tokens (or
            a fallback string when no AI text was emitted), *tool_call_count*
            is the total number of tool invocations, and *tool_error_count* is
            the number of invocations that returned ``status="error"``.
        """
        full_reply = ""
        last_tool_result: str = ""
        pending_tool_name: str = ""
        # Accumulates text tokens since the last tool call.
        # When stream_final_only=True, only this section is streamed (and only
        # after the loop ends), which prevents intermediate pre-tool narration
        # from leaking to the user.
        current_section: str = ""

        guard = ToolErrorGuard(max_consecutive=5, max_total=8)

        # No-op buffer when streaming is disabled
        async def _noop_callback(chunk: str) -> None:  # pragma: no cover
            pass

        buf = StreamBuffer(
            flush_threshold=STREAM_BUFFER_CHARS,
            callback=stream_callback if stream_callback is not None else _noop_callback,
        )

        stream_kwargs: dict = {
            "stream_mode": ["updates", "messages"],
            "subgraphs": True,
            "version": "v2",
        }
        if config is not None:
            stream_kwargs["config"] = config

        async with contextlib.aclosing(self._agent.astream(input_data, **stream_kwargs)) as stream:
            async for chunk in stream:
                if not (isinstance(chunk, dict) and "type" in chunk and "ns" in chunk and "data" in chunk):
                    logger.warning("Unexpected astream chunk shape: %s", type(chunk))
                    continue
                chunk_type = chunk["type"]
                ns = chunk["ns"]
                data = chunk["data"]
                source = f"subagent:{ns[0]}" if ns else "agent"

                # ── Step transitions ─────────────────────────────────────────
                if chunk_type == "updates":
                    for node_name in data:
                        if node_name in ("model", "tools"):
                            logger.debug("[%s] step: %s", source, node_name)
                        if node_name == "model" and ns:
                            # Subagent (non-root namespace) is starting an LLM call
                            if progress_callback is not None:
                                await progress_callback("subagent_start", source)

                # ── Message events ───────────────────────────────────────────
                elif chunk_type == "messages":
                    token, _metadata = data

                    # Tool call chunks — only AIMessageChunk has this attribute.
                    # Primary detection: token.tool_call_chunks (all providers).
                    # Fallback: content block with type=="tool_use" (langchain_anthropic
                    # extended-thinking mode emits both simultaneously; this catches
                    # providers that populate only the structured content block).
                    tool_call_chunks = getattr(token, "tool_call_chunks", None)
                    synthetic_fallback = False
                    if not tool_call_chunks:
                        # Fallback: detect tool_use block in structured content
                        tool_use_name = _has_tool_use_block(getattr(token, "content", None))
                        if tool_use_name:
                            tool_call_chunks = [{"name": tool_use_name, "args": ""}]
                            synthetic_fallback = True
                            logger.debug("[%s] tool_use block detected via content fallback: %s", source, tool_use_name)
                    if tool_call_chunks:
                        for tc in tool_call_chunks:
                            if tc.get("name"):
                                pending_tool_name = tc["name"]
                                logger.info("[%s] tool_call: %s", source, pending_tool_name)
                                if progress_callback is not None:
                                    await progress_callback("tool_call", pending_tool_name)
                                # Discard pre-tool narration: reset the current section
                                # so only the post-tool final reply is streamed.
                                if self._display.final_only:
                                    current_section = ""
                                # The synthetic fallback list always has exactly one entry
                                # (the first tool_use block name returned by
                                # _has_tool_use_block).  Break explicitly so any future
                                # mutation to that list cannot cause duplicate events.
                                if synthetic_fallback:
                                    break
                            if tc.get("args"):
                                args_preview = str(tc["args"])[:200]
                                logger.info(
                                    "[%s] tool_call_args [%s]: %s",
                                    source,
                                    pending_tool_name,
                                    args_preview,
                                )

                    # Tool result
                    if token.type == "tool":
                        tool_name = getattr(token, "name", "?")
                        normalised = _normalise_content(token.content)
                        last_tool_result = normalised
                        logger.info(
                            "[%s] tool_result [%s]: %s",
                            source,
                            tool_name,
                            normalised[:300],
                        )
                        if progress_callback is not None:
                            await progress_callback(
                                "tool_result",
                                f"{tool_name}: {normalised[:100]}",
                            )
                        # Loop guard: abort on too many errors (consecutive or total).
                        # DeepAgents marks execute ToolMessages with status="success" even when
                        # the command exits with a non-zero code — the exit code is only embedded
                        # in the text as "[Command failed with exit code N]". We detect that here
                        # so the loop guard fires on systematic shell failures too.
                        is_logical_error = getattr(token, "status", None) == "error" or (
                            tool_name == "execute" and _EXECUTE_FAILURE_MARKER in normalised
                        )
                        guard.record(tool_name, is_logical_error)

                    # Text tokens from the LLM.
                    # AIMessageChunk.type is "AIMessageChunk" in streaming (not "ai"),
                    # so we match any non-tool message that carries content.
                    # Note: tool_call_chunks and text content can coexist in the same
                    # AIMessageChunk (parallel tool call + narration), so we do NOT
                    # gate on the absence of tool_call_chunks.
                    if token.type != "tool" and token.content:
                        text = _normalise_content(token.content)
                        if text:
                            full_reply += text
                            current_section = await self._emit_text(text, buf, current_section)

                        current_section = await self._emit_thinking(token.content, buf, current_section)

        if stream_callback is not None:
            if self._display.final_only:
                # Stream only the final section (text after the last tool call).
                await buf.add(current_section)
            await buf.flush()

        # ── Fallback for models that do not emit a final AI text token ─────
        # (e.g. nemotron-mini / Ollama models that treat tool results as the reply)
        if not full_reply:
            if last_tool_result:
                logger.warning(
                    "No AI text token emitted — using last tool result as reply "
                    "(nemotron fallback). preview=%s",
                    last_tool_result[:80],
                )
                full_reply = last_tool_result
                current_section = last_tool_result
            else:
                logger.warning(
                    "No AI text token and no tool result — returning placeholder reply."
                )
                full_reply = REPLY_PLACEHOLDER
                current_section = REPLY_PLACEHOLDER

        # When final_only mode is active, return only the post-last-tool-call
        # text so that intermediate narration is excluded from the reply content.
        reply_text = current_section if self._display.final_only else full_reply
        return reply_text, guard.total_calls, guard.total_errors


    async def _emit_text(self, text: str, buf: StreamBuffer, current_section: str) -> str:
        """Emit a text token to the stream buffer or accumulate for final_only mode.

        Args:
            text: The text fragment to emit.
            buf: The StreamBuffer to write to when not in final_only mode.
            current_section: The accumulated text since the last tool call.

        Returns:
            The updated current_section string.
        """
        if self._display.final_only:
            return current_section + text
        await buf.add(text)
        return current_section

    async def _emit_thinking(self, raw: object, buf: StreamBuffer, current_section: str) -> str:
        """Emit a thinking token to the stream buffer if the thinking event is enabled.

        Thinking tokens are only emitted when ``events["thinking"]`` is True in the
        DisplayConfig. The token is wrapped in a blockquote for visual distinction.

        Behaviour depends on ``final_only``:

        - ``final_only=False`` (stream mode): the thinking block is pushed to ``buf``
          so it appears in the live token stream. It is NOT added to ``full_reply`` or
          ``current_section`` — the stored reply text will not contain thinking content.
        - ``final_only=True`` (block mode): the thinking block is appended to
          ``current_section`` and therefore included in the final reply sent to the
          channel. This is intentional and useful for debugging or transparency: the
          user receives the model's reasoning inline with the answer.

        Args:
            raw: The raw content field from a LangChain AIMessageChunk.
            buf: The StreamBuffer to write to when not in final_only mode.
            current_section: The accumulated text since the last tool call.

        Returns:
            The updated current_section string.
        """
        if not self._display.events.get("thinking", False):
            return current_section
        thinking = _extract_thinking(raw)
        if not thinking:
            return current_section
        wrapped = f"\n> *[thinking]* {thinking}\n"
        if self._display.final_only:
            return current_section + wrapped
        await buf.add(wrapped)
        return current_section


def _build_execution_context(envelope: Envelope) -> str:
    """Render envelope routing metadata as a plain-text context block.

    The block is prepended to the first user message on every agent turn so
    that skills which need routing information (e.g. ``channel-setup`` for
    WhatsApp pairing) can read the current ``sender_id``, ``channel``,
    ``session_id``, ``correlation_id`` and ``reply_to`` directly from the
    conversation state.

    The block is wrapped in explicit ``<relais_execution_context>`` tags so
    that the LLM recognises it as technical metadata and does NOT echo it
    back to the user.  Skills reference the tag by name.

    Args:
        envelope: The inbound envelope being processed.

    Returns:
        A formatted string ready to prepend to the user message, or an
        empty string if no metadata is available.
    """
    aig_ctx: AiguilleurCtx = envelope.context.get(CTX_AIGUILLEUR, {})  # type: ignore
    reply_to = aig_ctx.get("reply_to", "")
    lines = [
        "<relais_execution_context>",
        "This block is RELAIS pipeline metadata, not user input. Do NOT echo it.",
        "Use it only when a skill explicitly requires routing information.",
        f"sender_id: {envelope.sender_id}",
        f"channel: {envelope.channel}",
        f"session_id: {envelope.session_id}",
        f"correlation_id: {envelope.correlation_id}",
        f"reply_to: {reply_to}",
        "</relais_execution_context>",
    ]
    return "\n".join(lines)


def _enrich_system_prompt(soul_prompt: str, *, delegation_prompt: str = "") -> str:
    """Append operational rules to the assembled system prompt.

    Appends long-term memory instructions, self-diagnosis instructions
    for tool error recovery, and the delegation prompt (assembled by
    ``SubagentRegistry``) when non-empty.

    The self-diagnosis instructions tell the agent to stop and re-read
    the relevant SKILL.md troubleshooting section when encountering
    repeated tool errors, rather than blindly retrying.

    Args:
        soul_prompt: The base system prompt assembled by SoulAssembler.
        delegation_prompt: Pre-assembled delegation prompt from the
            subagent registry.  Empty string means no subagents.

    Returns:
        The enriched system prompt string.
    """
    parts = [soul_prompt.rstrip()]
    if LONG_TERM_MEMORY_PROMPT not in soul_prompt:
        parts.append(LONG_TERM_MEMORY_PROMPT)
    if SELF_DIAGNOSIS_PROMPT not in soul_prompt:
        parts.append(SELF_DIAGNOSIS_PROMPT)
    if delegation_prompt:
        parts.append(delegation_prompt)
    return "\n\n".join(parts)
