"""DeepAgents-based LLM executor for the Atelier brick.

Replaces SDKExecutor with a LangChain/DeepAgents agent that supports
native streaming (token-by-token) and multi-provider models.
"""

from __future__ import annotations

import asyncio
import logging
import os
from dataclasses import dataclass
from typing import Any, Callable, Awaitable, cast

from deepagents.backends import BackendProtocol, CompositeBackend, LocalShellBackend
from deepagents import SubAgent
from langchain_core.tools import BaseTool
from langchain_core.runnables import RunnableConfig
from langchain.chat_models import BaseChatModel, init_chat_model
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.checkpoint.memory import MemorySaver

from deepagents import create_deep_agent
from common.config_loader import get_relais_home
from common.profile_loader import ProfileConfig
from atelier.message_serializer import serialize_messages
from common.contexts import CTX_PORTAIL, PortailCtx
from common.envelope import Envelope

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class AgentResult:
    """Immutable result of a single agentic turn.

    Attributes:
        reply_text: The final text reply produced by the agent (may be an
            empty string when only tool calls were made).
        messages_raw: Serialized flat list of all LangChain messages captured
            from the agent graph state after the turn completes.  Each element
            is a JSON-serializable dict as produced by ``serialize_messages()``.
        tool_call_count: Total number of tool invocations during the turn.
        tool_error_count: Number of tool invocations that returned
            ``status="error"`` during the turn.
    """

    reply_text: str
    messages_raw: list[dict]
    tool_call_count: int = 0
    tool_error_count: int = 0


STREAM_BUFFER_CHARS = 80
REPLY_PLACEHOLDER = "[No response generated by the model.]"
LONG_TERM_MEMORY_PROMPT = """
Long-term memory:
- Any information about the user must be stored in the `memories` directory.
- This includes the user's preferences, needs, goals, projects, and any other user-related details.
- If the user asks you to remember anything, save it in `memories`.
- Always use paths like `/memories/...` to create, read, update, or organize persistent memories.
- Do not write long-term information outside `/memories/`.
- Before answering any question about the user or long-term memory, first check `/memories/` for relevant user and long-term information.
""".strip()


# Error class names raised by LLM providers (anthropic, openai, google, …) that
# indicate a transient condition — caller must NOT ACK the message so it stays in
# the PEL for automatic re-delivery.  We detect by name to stay provider-agnostic
# and avoid importing provider SDKs directly.
_TRANSIENT_ERROR_NAMES: frozenset[str] = frozenset(
    {
        "RateLimitError",
        "InternalServerError",
        "APIConnectionError",
        "APITimeoutError",
        "ServiceUnavailableError",
    }
)

# Substrings matched (case-insensitive) inside a ValueError message to detect
# upstream rate-limit or throttle errors forwarded as plain ValueError by
# proxy layers (e.g. OpenRouter wrapping Alibaba / other upstream providers).
_TRANSIENT_VALUE_ERROR_PATTERNS: tuple[str, ...] = (
    "rate limit",
    "rate increased too quickly",
    "too many requests",
    "upstream error",
    "code: 502",
    "code: 503",
    "overloaded",
)


def _resolve_profile_model(
    profile: ProfileConfig,
) -> BaseChatModel | str:
    """Build the model argument for create_deep_agent from a ProfileConfig.

    When both base_url and api_key_env are None, returns the model string
    directly so create_deep_agent can resolve the provider internally.
    When either is set, constructs a BaseChatModel via init_chat_model(),
    passing only the kwargs that are present.

    Args:
        profile: The resolved ProfileConfig for the current envelope.

    Returns:
        Either the model identifier string, or a pre-built BaseChatModel
        instance with the configured endpoint and credentials.

    Raises:
        KeyError: api_key_env is set but the environment variable is absent.
    """
    needs_init = (
        profile.base_url is not None
        or profile.api_key_env is not None
        or profile.parallel_tool_calls is not None
    )
    if not needs_init:
        return profile.model
    kwargs: dict[str, Any] = {}
    if profile.base_url is not None:
        kwargs["base_url"] = profile.base_url
    if profile.api_key_env is not None:
        api_key = os.environ.get(profile.api_key_env)
        if api_key is None:
            raise KeyError(
                f"Environment variable '{profile.api_key_env}' (required by profile "
                f"'{profile.model}') is not set."
            )
        kwargs["api_key"] = api_key
    if profile.parallel_tool_calls is not None:
        kwargs.setdefault("model_kwargs", {})["parallel_tool_calls"] = profile.parallel_tool_calls
    return init_chat_model(profile.model, **kwargs)


def _is_transient_provider_error(exc: BaseException) -> bool:
    """Return True if *exc* is a known transient provider error.

    Two detection strategies:
    - Class name match against ``_TRANSIENT_ERROR_NAMES`` (provider SDK errors).
    - Substring match on ``ValueError`` messages for proxy layers (e.g.
      OpenRouter forwarding upstream rate-limit / 502 errors as plain
      ``ValueError`` rather than a typed SDK exception).

    Args:
        exc: The exception to classify.

    Returns:
        True if the error is transient and the caller should not ACK the message.
    """
    if type(exc).__name__ in _TRANSIENT_ERROR_NAMES:
        return True
    if isinstance(exc, ValueError):
        msg = str(exc).lower()
        return any(pattern in msg for pattern in _TRANSIENT_VALUE_ERROR_PATTERNS)
    return False


def _normalise_content(raw: object) -> str:
    """Normalise a message content field to a plain string.

    Handles the three shapes LangChain message content can take:
    - ``str`` — returned as-is.
    - ``list`` — elements may be ``str`` (joined directly) or ``dict`` blocks
      (only ``{"type": "text", "text": "..."}`` blocks are extracted; other
      block types such as ``image_url`` are silently skipped).
    - anything else — converted via ``str()``.

    Args:
        raw: The raw ``.content`` value from a LangChain message.

    Returns:
        A plain string representation of the content.
    """
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        parts: list[str] = []
        for item in raw:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                parts.append(item["text"])
        return "".join(parts)
    return str(raw)


class AgentExecutionError(Exception):
    """Raised for permanent/unknown agent execution failures.

    Transient errors (RateLimitError, InternalServerError, APIConnectionError)
    are retried by ``AgentExecutor.execute()`` before being surfaced as
    ``ExhaustedRetriesError``.  Non-transient errors are wrapped immediately.

    Args:
        message: Human-readable error description.
        response_body: Optional raw response body from the LLM provider.
    """

    def __init__(self, message: str, response_body: str | None = None) -> None:
        super().__init__(message)
        self.response_body = response_body


class ExhaustedRetriesError(AgentExecutionError):
    """Raised when all retry attempts for a transient error are exhausted.

    Subclasses ``AgentExecutionError`` so ``_handle_envelope`` routes it to
    the DLQ and ACKs the message (avoids poisoning the PEL indefinitely).
    """


class AgentExecutor:
    """Execute LLM requests via a DeepAgents compiled state graph.

    Wraps `create_deep_agent` and exposes a single `execute()` coroutine
    that streams tokens and progress events via the v2 astream protocol.

    Args:
        profile: Profile config with at least a `.model` attribute
                 (format: ``provider:model-id``).
        soul_prompt: System prompt assembled by SoulAssembler.
        tools: List of LangChain tools (StructuredTool / BaseTool) to
               expose to the agent.
        skills: List of absolute directory paths to skill directories,
                passed directly to ``create_deep_agent(skills=...)``.
                Defaults to an empty list (no skills injected).
        backend: Optional backend instance used for ``/memories/`` paths
                 inside the ``CompositeBackend``.  When ``None`` (default),
                 a ``LocalShellBackend`` rooted at ``RELAIS_HOME`` is used
                 for both the default route and the ``/memories/`` route.
        checkpointer: LangGraph checkpoint saver for persistent conversation
                      history across turns.  When ``None`` (default), falls
                      back to a per-instance ``MemorySaver`` (volatile —
                      history lost on restart).  Pass an ``AsyncSqliteSaver``
                      owned by the Atelier singleton for cross-restart
                      persistence.
        subagents: List of SubAgent specs (dicts with ``name``,
                   ``description``, ``system_prompt``, and optionally
                   ``model``, ``tools``, ``skills``).  Each spec is
                   registered as a child agent invocable via the ``task``
                   tool.  Defaults to an empty list (no subagents).
        delegation_prompt: Pre-assembled delegation prompt from the
                   subagent registry.  Appended to the system prompt so
                   the main agent knows when to delegate via ``task()``.
                   Empty string means no delegation instructions.
    """

    def __init__(
        self,
        profile: ProfileConfig,
        soul_prompt: str,
        tools: list[BaseTool],
        skills: list[str] | None = None,
        backend: BackendProtocol | None = None,
        checkpointer: BaseCheckpointSaver | None = None,
        subagents: list[dict[str, Any]] | None = None,
        delegation_prompt: str = "",
    ) -> None:
        self._profile = profile
        memories_backend: BackendProtocol = backend or LocalShellBackend(
            root_dir=str(get_relais_home()), virtual_mode=False, inherit_env=True
        )
        composite_backend = CompositeBackend(
            default=LocalShellBackend(root_dir=str(get_relais_home()), virtual_mode=False, inherit_env=True),
            routes={
                "/memories/": memories_backend,
            },
        )
        # Convert dict subagent specs to SubAgent objects
        compiled_subagents: list[SubAgent] = [
            SubAgent(**spec) for spec in (subagents or [])
        ]
        self._agent = create_deep_agent(
            model=_resolve_profile_model(profile),
            tools=tools,
            system_prompt=_enrich_system_prompt(
                soul_prompt, delegation_prompt=delegation_prompt,
            ),
            skills=skills or [],
            backend=composite_backend,
            checkpointer=checkpointer or MemorySaver(),
            subagents=cast(list[SubAgent | Any], compiled_subagents),
        )

    async def execute(
        self,
        envelope: Envelope,
        stream_callback: Callable[[str], Awaitable[None]] | None = None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
    ) -> AgentResult:
        """Run the agent on *envelope* with retry-on-transient-error logic.

        Wraps ``_run_once()`` in a retry loop driven by the profile's
        ``resilience`` configuration.  On each transient error the coroutine
        sleeps for the configured backoff delay before retrying.  When all
        attempts are exhausted, raises ``ExhaustedRetriesError`` (a subclass
        of ``AgentExecutionError``) so the caller routes the message to the DLQ
        and ACKs it — preventing the PEL from being poisoned indefinitely.

        Non-transient errors are wrapped in ``AgentExecutionError`` immediately
        on the first attempt.

        Args:
            envelope: Incoming message envelope; `.content` is the user turn.
            stream_callback: Async callable receiving buffered text chunks.
                If ``None``, no token-by-token streaming is performed.
            progress_callback: Async callable receiving ``(event, detail)`` pairs
                that describe pipeline progress (tool calls, tool results, subagent
                starts).  If ``None``, progress events are only logged locally.

        Returns:
            An ``AgentResult`` containing the full reply text and the serialized
            message list for the completed turn.

        Raises:
            AgentExecutionError: Non-transient failure on the first attempt.
            ExhaustedRetriesError: All retry attempts exhausted on a transient error.
        """
        resilience = self._profile.resilience
        last_exc: BaseException | None = None

        for attempt in range(resilience.retry_attempts + 1):
            try:
                return await self._run_once(envelope, stream_callback, progress_callback)
            except AgentExecutionError:
                raise
            except Exception as exc:
                if not _is_transient_provider_error(exc):
                    raise AgentExecutionError(f"Agent execution failed: {exc}") from exc
                last_exc = exc
                if attempt < resilience.retry_attempts:
                    delay = (
                        resilience.retry_delays[
                            min(attempt, len(resilience.retry_delays) - 1)
                        ]
                        if resilience.retry_delays
                        else 0
                    )
                    logger.warning(
                        "[%s] Transient error (attempt %d/%d), retrying in %ds: %s",
                        envelope.correlation_id,
                        attempt + 1,
                        resilience.retry_attempts,
                        delay,
                        exc,
                    )
                    await asyncio.sleep(delay)

        raise ExhaustedRetriesError(
            f"All {resilience.retry_attempts} retries exhausted: {last_exc}"
        ) from last_exc

    async def _run_once(
        self,
        envelope: Envelope,
        stream_callback: Callable[[str], Awaitable[None]] | None = None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
    ) -> AgentResult:
        """Execute a single agent turn without retry logic.

        Builds the RunnableConfig, runs the astream loop, captures the final
        graph state, and returns the serialized result.  All exceptions
        propagate to the caller (``execute()``).

        Args:
            envelope: Incoming message envelope; `.content` is the user turn.
            stream_callback: Forwarded to ``_stream()``.
            progress_callback: Forwarded to ``_stream()``.

        Returns:
            An ``AgentResult`` for this single attempt.
        """
        messages = [{"role": "user", "content": envelope.content}]
        logger.info(
            "agent.execute start — correlation_id=%s sender=%s",
            envelope.correlation_id,
            envelope.sender_id,
        )
        portail_ctx: PortailCtx = envelope.context.get(CTX_PORTAIL, {})  # type: ignore
        user_id = portail_ctx.get("user_id", envelope.sender_id)
        config = RunnableConfig(configurable={"thread_id": user_id})
        reply, tool_call_count, tool_error_count = await self._stream(
            {"messages": messages}, stream_callback, progress_callback, config=config
        )
        # Capture full message list from the agent graph state.
        # aget_state() must not fail — if it does, it means the agent is
        # misconfigured (e.g. no checkpointer).  Propagate the exception
        # to execute(): transient errors are retried, others go to DLQ.
        state = await self._agent.aget_state(config)
        state_messages = state.values.get("messages", [])
        messages_raw = serialize_messages(state_messages)
        logger.info(
            "agent.execute done — correlation_id=%s reply_len=%d messages=%d "
            "tool_calls=%d tool_errors=%d",
            envelope.correlation_id,
            len(reply),
            len(messages_raw),
            tool_call_count,
            tool_error_count,
        )
        return AgentResult(
            reply_text=reply,
            messages_raw=messages_raw,
            tool_call_count=tool_call_count,
            tool_error_count=tool_error_count,
        )

    async def _stream(
        self,
        input_data: dict[str, list[dict[str, str]]],
        stream_callback: Callable[[str], Awaitable[None]] | None,
        progress_callback: Callable[[str, str], Awaitable[None]] | None = None,
        config: RunnableConfig | None = None,
    ) -> tuple[str, int, int]:
        """Stream tokens and events from the agent, logging all operations.

        Uses the v2 streaming format with ``stream_mode=["updates", "messages"]``
        and ``subgraphs=True`` to capture step transitions, tool calls, tool
        results, and text tokens from both the main agent and any subagents.

        When *stream_callback* is not None, text tokens are forwarded in
        buffered chunks (STREAM_BUFFER_CHARS threshold).

        When *progress_callback* is not None, it is called with ``(event, detail)``
        pairs for:
        - ``('tool_call', tool_name)`` — when a tool call is initiated.
        - ``('tool_result', 'name: preview')`` — when a tool result arrives
          (preview capped at 100 characters).
        - ``('subagent_start', source)`` — when a subagent starts an LLM call
          (only emitted for non-root namespaces).

        Falls back to the last ToolMessage content when the model emits no AI
        text tokens (nemotron-mini pattern).  Returns a placeholder constant
        when neither AI text nor tool results are available.

        Args:
            input_data: Input dict passed to ``agent.astream``.
            stream_callback: Async callable receiving flushed text chunks,
                or ``None`` for logging-only mode.
            progress_callback: Async callable receiving ``(event, detail)``
                pipeline progress pairs, or ``None`` to skip progress events.

        Returns:
            A 3-tuple of ``(reply, tool_call_count, tool_error_count)`` where
            *reply* is the complete text assembled from all streamed tokens (or
            a fallback string when no AI text was emitted), *tool_call_count*
            is the total number of tool invocations, and *tool_error_count* is
            the number of invocations that returned ``status="error"``.
        """
        buf = ""
        full_reply = ""
        last_tool_result: str = ""
        pending_tool_name: str = ""
        _consecutive_tool_error_name: str = ""
        _consecutive_tool_error_count: int = 0
        _TOOL_ERROR_LOOP_LIMIT: int = 5
        _tool_call_count: int = 0
        _tool_error_count: int = 0

        stream_kwargs: dict = {
            "stream_mode": ["updates", "messages"],
            "subgraphs": True,
            "version": "v2",
        }
        if config is not None:
            stream_kwargs["config"] = config

        async for chunk in self._agent.astream(input_data, **stream_kwargs):
            if not (isinstance(chunk, dict) and "type" in chunk and "ns" in chunk and "data" in chunk):
                logger.warning("Unexpected astream chunk shape: %s", type(chunk))
                continue
            chunk_type = chunk["type"]
            ns = chunk["ns"]
            data = chunk["data"]
            source = f"subagent:{ns[0]}" if ns else "agent"

            # ── Step transitions ─────────────────────────────────────────
            if chunk_type == "updates":
                for node_name in data:
                    if node_name in ("model", "tools"):
                        logger.debug("[%s] step: %s", source, node_name)
                    if node_name == "model" and ns:
                        # Subagent (non-root namespace) is starting an LLM call
                        if progress_callback is not None:
                            await progress_callback("subagent_start", source)

            # ── Message events ───────────────────────────────────────────
            elif chunk_type == "messages":
                token, _metadata = data

                # Tool call chunks — only AIMessageChunk has this attribute
                tool_call_chunks = getattr(token, "tool_call_chunks", None)
                if tool_call_chunks:
                    for tc in tool_call_chunks:
                        if tc.get("name"):
                            pending_tool_name = tc["name"]
                            logger.info("[%s] tool_call: %s", source, pending_tool_name)
                            if progress_callback is not None:
                                await progress_callback("tool_call", pending_tool_name)
                        if tc.get("args"):
                            logger.debug(
                                "[%s] tool_args [%s]: %s",
                                source,
                                pending_tool_name,
                                tc["args"],
                            )

                # Tool result
                if token.type == "tool":
                    tool_name = getattr(token, "name", "?")
                    normalised = _normalise_content(token.content)
                    last_tool_result = normalised
                    result_preview = normalised[:300]
                    _tool_call_count += 1
                    logger.info(
                        "[%s] tool_result [%s]: %s",
                        source,
                        tool_name,
                        result_preview,
                    )
                    if progress_callback is not None:
                        await progress_callback(
                            "tool_result",
                            f"{tool_name}: {normalised[:100]}",
                        )
                    # Loop guard: abort on repeated consecutive errors for the same tool.
                    # Unnamed tools (name == "?") are excluded — grouping them together
                    # could trigger a false abort when different tools all lack a name.
                    named_tool = tool_name if tool_name != "?" else None
                    if getattr(token, "status", None) == "error":
                        _tool_error_count += 1
                        if named_tool is not None and named_tool == _consecutive_tool_error_name:
                            _consecutive_tool_error_count += 1
                        elif named_tool is not None:
                            _consecutive_tool_error_name = named_tool
                            _consecutive_tool_error_count = 1
                        if _consecutive_tool_error_count >= _TOOL_ERROR_LOOP_LIMIT:
                            raise AgentExecutionError(
                                f"Tool '{tool_name}' errored {_consecutive_tool_error_count} "
                                f"consecutive times — aborting to prevent infinite loop. "
                                f"Last error: {normalised[:200]}"
                            )
                    else:
                        _consecutive_tool_error_name = ""
                        _consecutive_tool_error_count = 0

                # Text tokens from the LLM.
                # AIMessageChunk.type is "AIMessageChunk" in streaming (not "ai"),
                # so we match any non-tool message that carries content.
                # Note: tool_call_chunks and text content can coexist in the same
                # AIMessageChunk (parallel tool call + narration), so we do NOT
                # gate on the absence of tool_call_chunks.
                if token.type != "tool" and token.content:
                    text = _normalise_content(token.content)
                    if text:
                        full_reply += text
                        if stream_callback is not None:
                            buf += text
                            if len(buf) >= STREAM_BUFFER_CHARS:
                                await stream_callback(buf)
                                buf = ""

        if buf and stream_callback is not None:
            await stream_callback(buf)

        # ── Fallback for models that do not emit a final AI text token ─────
        # (e.g. nemotron-mini / Ollama models that treat tool results as the reply)
        if not full_reply:
            if last_tool_result:
                logger.warning(
                    "No AI text token emitted — using last tool result as reply "
                    "(nemotron fallback). preview=%s",
                    last_tool_result[:80],
                )
                full_reply = last_tool_result
            else:
                logger.warning(
                    "No AI text token and no tool result — returning placeholder reply."
                )
                full_reply = REPLY_PLACEHOLDER

        return full_reply, _tool_call_count, _tool_error_count


def _enrich_system_prompt(soul_prompt: str, *, delegation_prompt: str = "") -> str:
    """Append operational rules to the assembled system prompt.

    Appends long-term memory instructions unconditionally, and the
    delegation prompt (assembled by ``SubagentRegistry``) when non-empty.

    Args:
        soul_prompt: The base system prompt assembled by SoulAssembler.
        delegation_prompt: Pre-assembled delegation prompt from the
            subagent registry.  Empty string means no subagents.

    Returns:
        The enriched system prompt string.
    """
    parts = [soul_prompt.rstrip()]
    if LONG_TERM_MEMORY_PROMPT not in soul_prompt:
        parts.append(LONG_TERM_MEMORY_PROMPT)
    if delegation_prompt:
        parts.append(delegation_prompt)
    return "\n\n".join(parts)
