"""Streaming utilities for the Atelier agent executor.

Provides content-extraction helpers used by ``AgentExecutor._stream()`` to
handle LangChain / DeepAgents streaming output.  Also provides content
normalisation utilities and sentinel constants.

Classes:
    TaskArgsTracker: Accumulates ``task`` tool-call argument fragments to
        extract the subagent name from streamed JSON, maintaining a namespace-
        ID to subagent-name mapping across a single ``_stream()`` call.
    ChunkPayload: Parsed and validated DeepAgents astream v2 chunk (NamedTuple).

Functions:
    decode_chunk: Validate and decode a raw DeepAgents astream v2 chunk dict;
        returns ``None`` for non-conforming input so callers can skip unknown
        shapes with a simple ``if payload is None: continue`` guard.
"""

from __future__ import annotations

import json as _json
from typing import Any, NamedTuple

REPLY_PLACEHOLDER = "[No response generated by the model.]"

# Marker injected by DeepAgents FilesystemMiddleware into the execute tool's text output
# when the shell command exits with a non-zero code. Used to detect logical failures
# on ToolMessages that carry status="success" at the LangChain level.
_EXECUTE_FAILURE_MARKER = "[Command failed with exit code"


def _normalise_content(raw: object) -> str:
    """Normalise a message content field to a plain string.

    Handles the three shapes LangChain message content can take:
    - ``str`` — returned as-is.
    - ``list`` — elements may be ``str`` (joined directly) or ``dict`` blocks
      (only ``{"type": "text", "text": "..."}`` blocks are extracted; other
      block types such as ``image_url``, ``thinking``, ``tool_use`` are
      silently skipped).
    - anything else — converted via ``str()``.

    Args:
        raw: The raw ``.content`` value from a LangChain message.

    Returns:
        A plain string representation of the content.
    """
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        parts: list[str] = []
        for item in raw:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                parts.append(item["text"])
        return "".join(parts)
    return str(raw)

_BLOCK_PAYLOAD_KEY: dict[str, str] = {"thinking": "thinking", "tool_use": "name"}


def _extract_block_type(raw: object, block_type: str) -> list[str]:
    """Collect payload strings from all blocks of a given ``type`` in a content list.

    Iterates *raw* (expected to be a list of dicts) and returns the value of
    the payload field associated with *block_type*:

    - ``"thinking"`` blocks → value of the ``"thinking"`` key.
    - ``"tool_use"`` blocks → value of the ``"name"`` key.

    Non-list input, non-dict items, and items with a mismatched ``"type"``
    field are silently skipped.

    Args:
        raw: The raw ``.content`` value from a LangChain ``AIMessageChunk``.
        block_type: The ``"type"`` discriminant to match (e.g. ``"thinking"``,
            ``"tool_use"``).

    Returns:
        List of non-empty payload strings extracted from matching blocks.
        Returns an empty list when *raw* is not a list or no blocks match.
    """
    if not isinstance(raw, list):
        return []

    payload_key = _BLOCK_PAYLOAD_KEY.get(block_type, block_type)

    parts: list[str] = []
    for item in raw:
        if isinstance(item, dict) and item.get("type") == block_type:
            value = item.get(payload_key, "")
            if value:
                parts.append(str(value))
    return parts


def _extract_thinking(raw: object) -> str:
    """Extract thinking/reflection text from a structured content block list.

    When ``langchain_anthropic`` is configured with extended thinking enabled
    (``thinking={"type": "enabled", ...}``), it emits structured content blocks
    instead of a plain string.  Thinking deltas carry
    ``{"type": "thinking", "thinking": "..."}`` entries alongside text blocks.

    This function is the counterpart of ``_normalise_content``: where that
    function extracts ``type == "text"`` blocks, this one extracts
    ``type == "thinking"`` blocks.  Non-list content (str, other) returns "".

    Args:
        raw: The raw ``.content`` value from a LangChain ``AIMessageChunk``.

    Returns:
        Concatenated thinking text, or empty string if none found.
    """
    return "".join(_extract_block_type(raw, "thinking"))


def _has_named_tool_call_start(token: Any) -> bool:
    """Return True if *token* starts a new named tool call.

    A named tool call chunk signals the agent is beginning a new tool
    invocation.  Pre-flushing the stream buffer at this boundary ensures
    any buffered narration text reaches the client before the tool runs.

    Args:
        token: A LangChain ``AIMessageChunk``.

    Returns:
        True if ``token.tool_call_chunks`` contains at least one entry with
        a non-empty ``name`` field.
    """
    tcc = getattr(token, "tool_call_chunks", None)
    return bool(tcc and any(tc.get("name") for tc in tcc))


def _has_tool_use_block(raw: object) -> str | None:
    """Return the tool name if the content list contains a ``tool_use`` block.

    ``langchain_anthropic`` emits both ``token.tool_call_chunks`` and a
    ``{"type": "tool_use", "name": "...", ...}`` block in the content list
    simultaneously.  This function provides a fallback detection path for
    providers that populate the structured content block but leave
    ``tool_call_chunks`` empty.

    Args:
        raw: The raw ``.content`` value from a LangChain ``AIMessageChunk``.

    Returns:
        The tool name string if a ``tool_use`` block with a non-empty ``name``
        is found, otherwise ``None``.
    """
    names = _extract_block_type(raw, "tool_use")
    return names[0] if names else None


class TaskArgsTracker:
    """Accumulates streamed ``task`` tool-call argument tokens to extract the subagent name.

    The DeepAgents ``task`` tool streams its JSON arguments token-by-token.
    This class buffers those fragments, attempts to parse them incrementally,
    and maintains a namespace-ID → subagent-name mapping across the lifetime
    of a single ``_stream()`` call.

    Attributes:
        buf: Accumulated JSON fragment for the current ``task`` call.
        name_logged: Whether the subagent name for the current call has been logged.
        ns_to_name: Mapping from DeepAgents namespace ID to declared subagent name.
    """

    def __init__(self) -> None:
        self.buf: str = ""
        self.name_logged: bool = False
        self.ns_to_name: dict[str, str] = {}

    def reset(self) -> None:
        """Reset the argument buffer and name-logged flag for a new ``task`` call.

        The ``ns_to_name`` mapping is preserved — subagent names registered in
        earlier task calls remain available for the rest of the stream.
        """
        self.buf = ""
        self.name_logged = False

    def accumulate(self, fragment: str) -> None:
        """Append an argument fragment to the buffer.

        Args:
            fragment: A token string from a ``tool_call_chunk`` args field.
        """
        self.buf += fragment

    def try_parse_name(self) -> str | None:
        """Attempt to parse the subagent name from the current buffer.

        Tries to JSON-decode the accumulated buffer and extract the ``name``
        field (preferred) or the ``subagent_type`` field (fallback).

        Returns:
            The subagent name string if parseable and non-empty, otherwise ``None``.
        """
        if not self.buf:
            return None
        try:
            parsed = _json.loads(self.buf)
            name = parsed.get("name", "") or parsed.get("subagent_type", "")
            return name if name else None
        except Exception:
            return None

    def register_ns(self, ns_id: str, name: str) -> None:
        """Store the resolved name for a DeepAgents namespace ID.

        Args:
            ns_id: The namespace identifier string from the stream chunk ``ns`` field.
            name: The human-readable subagent name to associate with this namespace.
        """
        self.ns_to_name[ns_id] = name

    def has_ns(self, ns_id: str) -> bool:
        """Return True if a name has been registered for *ns_id*.

        Args:
            ns_id: The namespace identifier to check.

        Returns:
            True if a mapping exists, False otherwise.
        """
        return ns_id in self.ns_to_name

    def get_name_for_ns(self, ns_id: str) -> str:
        """Return the registered name for *ns_id*, falling back to *ns_id* itself.

        Args:
            ns_id: The namespace identifier to look up.

        Returns:
            The registered name, or *ns_id* if no mapping exists.
        """
        return self.ns_to_name.get(ns_id, ns_id)


class ChunkPayload(NamedTuple):
    """Parsed and validated DeepAgents astream v2 chunk.

    Attributes:
        chunk_type: The ``"type"`` discriminant from the raw dict (``"updates"``
            or ``"messages"``).
        ns: The ``"ns"`` list from the raw dict (empty = root agent, non-empty =
            subagent namespace stack).
        data: The ``"data"`` payload — dict for ``"updates"``, (token, meta)
            tuple for ``"messages"``.
        source: Human-readable label derived from *ns*: ``"agent"`` when *ns*
            is empty, ``"subagent:{ns[0]}"`` otherwise.
    """

    chunk_type: str
    ns: list[str]
    data: Any

    @property
    def source(self) -> str:
        """Human-readable source label for logging."""
        return f"subagent:{self.ns[0]}" if self.ns else "agent"


def decode_chunk(raw: object) -> ChunkPayload | None:
    """Validate and decode a raw DeepAgents astream v2 chunk dict.

    Returns ``None`` for any input that does not conform to the expected
    ``{"type": ..., "ns": ..., "data": ...}`` shape so that callers can skip
    unknown shapes with a simple ``if payload is None: continue`` guard.

    Args:
        raw: The raw object received from ``agent.astream()``.

    Returns:
        A ``ChunkPayload`` named-tuple if *raw* is a valid chunk dict,
        otherwise ``None``.
    """
    if not isinstance(raw, dict):
        return None
    if not ("type" in raw and "ns" in raw and "data" in raw):
        return None
    return ChunkPayload(
        chunk_type=raw["type"],
        ns=raw["ns"],
        data=raw["data"],
    )
